# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' rcpp_hello_world.
#'
#' A example of a function written in C++.
#'
#' These are further details.
#'
#' @section Headers:
#'
#' Note header is pure C++, is not exported to RCpp or to NAMESPACE. Is usage is completely internal.
#'
#' @param x A description of the parameter 'x'. The
#'   description can span multiple lines.
#' @param y A description of the parameter 'y'.
#'
#' @export
rcpp_hello_world <- function() {
    .Call('_rcppSkeleton_rcpp_hello_world', PACKAGE = 'rcppSkeleton')
}

